// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;
import eud.wpi.first.wpilibj
/** Add your docs here. */
public class CANdle {
    // Example usage of a CANdle
 CANdle candle = new CANdle(0); // creates a new CANdle with ID 0

 CANdleConfiguration config = new CANdleConfiguration();
 config.stripType = LEDStripType.RGB; // set the strip type to RGB
 config.brightnessScalar = 0.5; // dim the LEDs to half brightness
 candle.configAllSettings(config);

 candle.setLEDs(255, 255, 255); // set the CANdle LEDs to white

 // create a rainbow animation:
 // - max brightness
 // - half speed
 // - 64 LEDs
 RainbowAnimation rainbowAnim = new RainbowAnimation(1, 0.5, 14);
 candle.animate(rainbowAnim);

 ErrorCode error = candle.getLastError(); // gets the last error generated by the CANdle
 CANdleFaults faults = new CANdleFaults();
 ErrorCode faultsError = candle.getFaults(faults); // fills faults with the current CANdle faults; returns the last error generated
 
}
